CREATE DATABASE "keycloak_db" ENCODING = 'UTF8' LOCALE_PROVIDER = libc;

CREATE DATABASE "user_service_db" ENCODING = 'UTF8' LOCALE_PROVIDER = libc;
CREATE DATABASE "chat_service_db" ENCODING = 'UTF8' LOCALE_PROVIDER = libc;
CREATE DATABASE "feed_service_db" ENCODING = 'UTF8' LOCALE_PROVIDER = libc;
CREATE DATABASE "notification_service_db" ENCODING = 'UTF8' LOCALE_PROVIDER = libc;